### ISSUE TITLE
sqli-lab-04.py: Maybe automatically-get the lab-provided random string from the page?

### ISSUE THREAD

**Issue by correabuscar** [rkhal101/Web-Security-Academy-Series#5]
https://github.com/rkhal101/Web-Security-Academy-Series/blob/a36dae4d5175d291f000ce711a7ea64a3e2269a3/sql-injection/lab-04/sqli-lab-04.py#L22

maybe via beautifulsoup like you did [here](https://www.youtube.com/watch?v=fMPvCyD2v4w&t=24m30s) ?

context: https://www.youtube.com/watch?v=mQquf6AHgZ4&t=21m10s

**Comment by Codingmogule** [comment]
'UNION SELECT 'a',NULL,NULL--
and replace each null with any letter 
Provided the number of columns is 3?

**Comment by correabuscar** [comment]
> 'UNION SELECT 'a',NULL,NULL-- and replace each null with any letter Provided the number of columns is 3?

@Codingmogule I'm referring to the text `Make the database retrieve the string 'v2F6UA'` that you can see, on the left on the WebSecurity Academy website, if you open up this video and pause it https://www.youtube.com/watch?v=mQquf6AHgZ4&t=21m10s . It's the goal that they want you to achieve in order for you to solve the lab.

This python script did hardcode that exact string, but that string will change every time the lab is started. So I figured maybe having the python script read that script from the webpage would make life easier for the script user :)

**Comment by correabuscar** [comment]
Actually I'm thinking that one the youtube video is made, there's a desire to not modify the python scripts later on, as to keep them in sync with the video. Thus I'm closing this issue.
